schema_version = "1.0.0"
id = "io_scene_bf2"
version = "0.8.6"
name = "Battlefield 2"
tagline = "Import and export asset files for DICE's Refractor 2 engine"
maintainer = "Marek Zajac <marekzajac97@gmail.com>"
type = "add-on"

website = "https://github.com/marekzajac97/bf2-blender"
tags = ["Game Engine", "Import-Export"]
blender_version_min = "4.2.0"
# blender_version_max = "5.0.0"

license = [
  "SPDX:MIT",
]

platforms = ["windows-x64", "macos-x64", "linux-x64"]

[build]
paths_exclude_pattern = [
  "/.git/",
  "__pycache__/",
]

[permissions]
files = "Import/export asset files from/to disk"
